name: lab2_hw1_
dependencies:
  - python=3.10.11
  - pip
  - pip: 
    - pandas==1.5.3
    - numpy==1.24.3
    - xgboost==1.7.3
    - scikit-learn
    - matplotlib
    - seaborn
    - scipy
    - hyperopt

 
