name: hw1_env
dependencies:
  - python=3.8
  - pip
  - pip:
    - numpy == 1.20.2
    - pandas == 1.2.4
    - absl-py==1.4.0
    - anaconda-client==1.7.2
    - anaconda-navigator==2.0.3
    - anaconda-project
    - appdirs==1.4.4
    - argh==0.26.2
    - astunparse==1.6.3
    - atomicwrites==1.4.0
    - backports.weakref==1.0.post1
    - bkcharts==0.2
    - black==19.10b0
    - boto==2.49.0
    - Bottleneck==1.3.2
    - brotlipy==0.7.0
    - cachetools==5.3.0
    - certifi==2020.12.5
    - clyent==1.2.2
    - conda==4.10.1
    - conda-build==3.21.4
    - conda-verify==3.4.2
    - contextlib2==0.6.0.post1
    - cycler==0.10.0
    - cytoolz==0.11.0
    - entrypoints==0.3
    - et-xmlfile==1.0.1
    - fastcache==1.1.0
    - flatbuffers==23.3.3
    - future==0.18.2
    - gast==0.4.0
    - gmpy2==2.0.8
    - google-auth==2.17.3
    - google-auth-oauthlib==1.0.0
    - google-pasta==0.2.0
    - grpcio==1.54.0
    - h5py==2.10.0
    - HeapDict==1.0.1
    - importlib-metadata==6.6.0
    - jax==0.4.8
    - jdcal==1.4.1
    - json5==0.9.5
    - jupyter==1.0.0
    - keras==2.12.0
    - libclang==16.0.0
    - llvmlite==0.36.0
    - locket==0.2.1
    - Markdown==3.4.3
    - MarkupSafe==1.1.1
    - mccabe==0.6.1
    - mistune==0.8.4
    - mkl-fft==1.3.0
    - mkl-service==2.3.0
    - ml-dtypes==0.1.0
    - mpmath==1.2.1
    - multipledispatch==0.6.0
    - mypy-extensions==0.4.3
    - navigator-updater==0.2.1
    - numpy==1.23.5
    - oauthlib==3.2.2
    - olefile==0.46
    - opt-einsum==3.3.0
    - pandas==1.2.4
    - parso==0.7.0
    - pathspec==0.7.0
    - patsy==0.5.1
    - pep8==1.7.1
    - pkginfo==1.7.0
    - ply==3.11
    - protobuf==4.22.3
    - py
    - pyasn1==0.5.0
    - pyasn1-modules==0.3.0
    - pycosat==0.6.3
    - pycurl==7.43.0.6
    - pyodbc===4.0.0-unsupported
    - pytest==6.2.3
    - PyYAML==5.4.1
    - pyzmq==20.0.0
    - QDarkStyle==2.8.1
    - QtPy==1.9.0
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - ruamel-yaml-conda @ file:///tmp/build/80754af9/ruamel_yaml_1616016699510/work
    - scikit-image==0.18.1
    - scikit-learn
    - scipy==1.10.1
    - simplegeneric==0.8.1
    - sip==4.19.13
    - tables==3.6.1
    - tensorboard==2.12.2
    - tensorboard-data-server==0.7.0
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.12.0
    - tensorflow-estimator==2.12.0
    - tensorflow-io-gcs-filesystem==0.32.0
    - termcolor==2.3.0
    - terminado==0.9.4
    - tifffile==2020.10.1
    - webencodings==0.5.1
    - widgetsnbextension==3.5.1
    - wrapt==1.12.1
    - xgboost==1.7.5
    - xlwt==1.3.0
    - xmltodict==0.12.0
    - zict==2.0.0
    - zope.event==4.5.0




